## Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

## General
minecraft_version=1.21.1
mod_version=6.0.2
modrinth_id=H1x2EwLg
curseforge_id=383182

## NeoForge
neoforge_version=21.1.219
parchment_version=2024.11.17

## Deps
mekanism_version=1.21.1-10.7.17.83

## CurseForge Deps
# 1.21-7.0.6
xnet_fileId=6563957
# 1.21-6.0.8
rftoolsbase_fileId=6762657
# 1.21-9.0.10
mcjtylib_fileId=6762654
