modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/Terrails/xnet-gases/issues"

[[mods]]
modId="xnetgases"
version="${file.jarVersion}"
displayName="XNet Gases"
logoFile="xnetgases.png"
credits="Credits go to bradyaidanc, McJty and other contributors for creating and working on Mekanism and XNet"
authors="Terrails"
description=''' A simple addon for XNet that enables the movement of chemicals from Mekanism. '''

[[dependencies.xnetgases]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.xnetgases]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.xnetgases]]
    modId="mekanism"
    type="required"
    versionRange="[1.21.1-10,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.xnetgases]]
    modId="xnet"
    type="required"
    versionRange="[1.21-7,)"
    ordering="AFTER"
    side="BOTH"